### PR TITLE
revise demo app for automated testing

### PR DESCRIPTION
**Pull request by mnbogner**
This PR revises the demo app to more accurately test the current state of the Envoy library, and also includes changes to the gradle files required to build the app in recent versions of Android Studio.

### CODE REVIEW

**Comment by vitriolix** [comment]
did you mean to have TLA's commits in here?

**Comment by mnbogner** [comment]
> did you mean to have TLA's commits in here?

yes, those changes are needed to compile this in current versions of android studio (which became necessary for me when i tried to work on the project on a different pc).  we decided to set aside his pr in favor of this one.

**Comment by vitriolix** [comment]
after mucking with the deps it works for me and looks fine, 🐿️

**Review by vitriolix — APPROVED** [review]

**Comment by vitriolix** [comment]
cmd line build worked for me after i upgraded to java 17 :shipit:

**Pull request merged**
